spring.application.name=proj2

# URL de Conexao (JDBC format)
spring.datasource.url=jdbc:postgresql://dpg-d7nu34hf9bms738panjg-a.frankfurt-postgres.render.com:5432/taca_lab?sslmode=require

# Credenciais
spring.datasource.username=manuca17
spring.datasource.password=wdwb7IGnUzigxmHtPVdve5vxozEtzYU9

# Configuracoes do Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Recomenda-se forcar o uso de SSL para conexoes externas ao Render
# (sslmode ja esta incluido na linha spring.datasource.url)